version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: nadi-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: nadi
    volumes:
      - mongo_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - nadi-network

  mongo-express:
    image: mongo-express:1.0.0
    container_name: nadi-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongo
    networks:
      - nadi-network

  # Redis (optional for future rate limiting/queues)
  # redis:
  #   image: redis:7.2-alpine
  #   container_name: nadi-redis
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - nadi-network

volumes:
  mongo_data:
  # redis_data:

networks:
  nadi-network:
    driver: bridge
